const data = {
  products: [
    {
      _id: "1",
      name: "Adidas Shoe",
      category: "Shoe",
      image: "/images/AdidasShoeBlack.jpg",
      price: 60,
      countInStock: 7,
      brand: "Adidas",
      ratings: 4.5,
      numberOfReviews: 15,
      description: "High quality shoe with black color",
    },
    {
      _id: "2",
      name: "Pearl Earlobe",
      category: "Jewellery",
      image: "/images/earlobe.jpg",
      price: 106,
      countInStock: 5,
      brand: "Amin Jewellers",
      ratings: 4,
      numberOfReviews: 5,
      description: "White pearl earlobe, made with high quality pearl",
    },
    {
      _id: "3",
      name: "Diamond Ring",
      category: "Jewellery",
      image: "/images/ring.jpg",
      price: 160,
      countInStock: 3,
      brand: "Purobi Jwellers",
      ratings: 5,
      numberOfReviews: 2,
      description: "Ring with top grade diamond on it",
    },
    {
      _id: "4",
      name: "Check Shirt",
      category: "Shirt",
      image: "/images/shirtNew.jpg",
      price: 80,
      countInStock: 15,
      brand: "Cats Eye",
      ratings: 4.5,
      numberOfReviews: 20,
      description: "Checkh shirt",
    },
    {
      _id: "5",
      name: "Mi Smart Band 5",
      category: "Accessory",
      image: "/images/watch.jpg",
      price: 30,
      countInStock: 10,
      brand: "Mi",
      ratings: 4,
      numberOfReviews: 7,
      description: "Smart watch with a lot of features",
    },
    {
      _id: "6",
      name: "Green T-shirt",
      category: "T-shirt",
      image: "/images/t-shirt.jpg",
      price: 55,
      countInStock: 0,
      brand: "Husky",
      ratings: 3.5,
      numberOfReviews: 60,
      description: "Green husky t-shirt",
    },
  ],
};
export default data;
